### ISSUE TITLE
I translated the plugin to Spanish

### ISSUE THREAD

**Issue by LycanrockZ** [olios123/BackInPack#1]
I have followed the instructions and I already have it in Spanish, I want to pass it on translated so that Spanish and Latin American people can use the plugin better :D .Mais le problème est que lorsque je l'utilise, je n'obtiens rien non plus dans le chat lorsque je mets la commande help.[https://www.mediafire.com/file/vegudqhxxrppd02/es.yml/file](url)

**Comment by olios123** [comment]
Wow, thanks a lot, I'll check the file and post an update in a while. Thanks

**Comment by LycanrockZ** [comment]
> Wow, muchas gracias, revisaré el archivo y publicaré una actualización en un momento. Gracias

I'm checking it because I just started it but when I put /backinpack nothing appears

**Comment by olios123** [comment]
And in the config.yml file you changed "language" to "es" ?

**Comment by LycanrockZ** [comment]
Si

**Comment by olios123** [comment]
Restarted the server?

**Comment by LycanrockZ** [comment]
Yes

**Comment by olios123** [comment]
One second, I'll check what could be wrong

**Comment by olios123** [comment]
![obraz](https://user-images.githubusercontent.com/71970315/235196674-9ec7aa91-cbb7-4028-96ee-d2ea1ee62258.png)

There are problems here.

The extra dot and hyphens should line up.

**Comment by LycanrockZ** [comment]
Thanks, I was already downloading the visual to see it better ;D and now it will be in Spanish for many more people

**Comment by olios123** [comment]
Here is your patched file https://www.mediafire.com/file/a95m72yywkh1r7r/es.yml/file

**Comment by LycanrockZ** [comment]
Thanks

**Comment by olios123** [comment]
Thank you again for your commitment

**Comment by LycanrockZ** [comment]
I have updated it because it did not take the tildes, neither did the ñ but I have removed the tildes [https://www.mediafire.com/file/y6yb81kboi33f6x/es.yml/file](url)

**Comment by olios123** [comment]
Okay, thanks

**Comment by LycanrockZ** [comment]
Sorry, I forgot to translate a command but that's it [https://www.mediafire.com/file/q4u1zcuojq03rvv/es.yml/file](url)

**Comment by olios123** [comment]
You don't have to apologize for anything
